import random
def register_customer():
    name = input("Enter customer name: ")
    address = input("Enter customer address: ")
    account_type = input("Enter account type (Saving or Current): ")
    account_number = random.randint(1000000000000000, 9999999999999999)
    password = input("Enter a password : ")
    print("-"*30)
    print("Customer registered successfully.")
    print("-"*30)
    print("Thank You For Creating Account In Our Bank.")
    print("-"*30)
    print("Customer Name Is :", name)
    print("Costumers Address Is : ", address)
    print("Your Account Number Is :", account_number)
    print("Your Password is : ", password)
    print(f"You Create {account_type} Account.")
    print("-"*30)
register_customer()
